DROP TABLE IF EXISTS TESTING;
CREATE TABLE TESTING(
 id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 nombre VARCHAR(10) NOT NULL,
 gender VARCHAR(10) NOT NULL,
 age INTEGER NOT NULL,
 address VARCHAR(20) NOT NULL,
 phone VARCHAR(10) NOT NULL
)